version: 0.2
env:
  variables:
    SBT_VERSION: "1.3.8"
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo `pwd`
      - curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
      - dpkg -i sbt-$SBT_VERSION.deb
      - sbt sbtVersion
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - printenv
      - sbt clean universal:stage
artifacts:
  files:
    - '**/*'
  base-directory: target/universal/stage
