version: 0.2
env:
  variables:
    SBT_VERSION: "1.5.5"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - sbt sbtVersion
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - printenv
      - sbt clean docker:stage
artifacts:
  files:
    - Dockerfile
    - opt/**/*
  base-directory: target/docker/stage
