AWSTemplateFormatVersion: '2010-09-09'

Description: CodePipeline with Secrets Manager

Parameters:
  CodeBuildEnvironment:
    Type: String
    Description: CodeBuild environment size
    Default: BUILD_GENERAL1_SMALL
    # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE

  RepositoryName:
    Type: String
    Description: Repository name
    Default: ref-app
    MinLength: 1
    MaxLength: 256
    AllowedPattern: '[a-zA-Z0-9][-a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  Branch:
    Type: String
    Description: GitHub branch to build
    MinLength: 1
    MaxLength: 256
    Default: master

  ApplicationName:
    Type: String
    Description: Beanstalk application name
    MinLength: 1
    MaxLength: 256
    AllowedPattern: '[a-zA-Z0-9][-a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  BeanstalkEnvironment:
    Type: String
    Description: Beanstalk environment
    MinLength: 1
    MaxLength: 256
    AllowedPattern: '[a-zA-Z0-9][-a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  BeanstalkPlatform:
    Type: String
    Description: Beanstalk Platform - docker or java
    Default: docker
    AllowedValues:
      - docker
      - java

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Application Source
        Parameters:
          - RepositoryName
          - Branch
      - Label:
          default: Build Image
        Parameters:
          - CodeBuildEnvironment
      - Label:
          default: Deployment Target
        Parameters:
          - ApplicationName
          - BeanstalkEnvironment
          - BeanstalkPlatform

Conditions:

  IsDocker: !Equals [ !Ref BeanstalkPlatform, docker ]

Resources:

  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Join [" ", ["Repository for", !Ref RepositoryName ]]
      RepositoryName: !Ref RepositoryName

  CloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref AppPipeline ] ]

  CloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref RepositoryName ] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - master
      Targets:
        - Arn:
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref AppPipeline ] ]
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: codepipeline-AppPipeline

  AppCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      Description: Builds the project
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !Ref CodeBuildEnvironment
        Image: 'aws/codebuild/standard:4.0'
      Source:
        BuildSpec: !If [ IsDocker, buildspec.yml, buildspec-java.yml ]
        Type: CODEPIPELINE
      TimeoutInMinutes: 30

  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    # DependsOn: BeanstalkEnvironment
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          Namespace: code
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeCommit
          OutputArtifacts:
          - Name: MyApp
          Configuration:
            RepositoryName: !Ref RepositoryName
            BranchName: !Ref Branch
            PollForSourceChanges: false
          RunOrder: 1
      - Name: Build
        Actions:
        - InputArtifacts:
          - Name: MyApp
          Name: CodeBuild
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref AppCodeBuild
          OutputArtifacts:
          - Name: MyAppBuild
          RunOrder: 1
      - Name: Staging
        Actions:
        - InputArtifacts:
          - Name: MyAppBuild
          Name: !Ref BeanstalkEnvironment
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: ElasticBeanstalk
          OutputArtifacts: []
          Configuration:
            ApplicationName: !Ref ApplicationName
            EnvironmentName: !Ref BeanstalkEnvironment
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreS3Bucket

  ArtifactStoreS3Bucket:
    Type: AWS::S3::Bucket
    # For Amazon S3 buckets, you must delete all objects in the bucket for deletion to succeed
    DeletionPolicy: Retain

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
